#!/bin/sh
## CCD Discovery Component for X3D Toggle Project
##
## `ccd.sh`
##
## Identifies the V-Cache CCD by mapping the L3 cache boundary of Core 0.

_l_dir_lib="$(cd "$(dirname "$0")" && pwd)"
. "$_l_dir_lib/framework.sh"

if [ "$X3D_FRAMEWORK" != "1" ] && [ "$X3D_EXEC" != "1" ]; then
    journal_write -37
fi

CCD0_CORES=""
for idx in /sys/devices/system/cpu/cpu0/cache/index*; do
    if [ -f "$idx/level" ]; then
        read -r level < "$idx/level"
        if [ "$level" = "3" ]; then
            read -r CCD0_CORES < "$idx/shared_cpu_list"
            break
        fi
    fi
done

if [ -z "$CCD0_CORES" ]; then
    PKG_SIBLINGS="/sys/devices/system/cpu/cpu0/topology/package_cpus_list"
    if [ -f "$PKG_SIBLINGS" ]; then
        read -r CCD0_CORES < "$PKG_SIBLINGS"
    fi
fi

if [ -z "$CCD0_CORES" ]; then
    CCD0_CORES="0-7"
fi

_l_OP="$1"
if { [ "$_l_OP" = "--gen-config" ] || [ "$_l_OP" = "--gen-h" ] || [ "$_l_OP" = "--gen-ccd" ]; } && [ "$(basename -- "$0")" = "ccd.sh" ]; then
    if [ "$X3D_EXEC" != "1" ]; then exit 1; fi
    CCD1_START=8
    
    case "$CCD0_CORES" in
        [0-9]*-[0-9]*)
            _l_tmp="${CCD0_CORES#*-}"
            _l_end="${_l_tmp%%,*}"
            CCD1_START=$(( _l_end + 1 ))
            ;;
    esac
    
    set -- /sys/devices/system/cpu/cpu[0-9]*
    TOTAL_CORES=$#
fi

if [ "$_l_OP" = "--gen-h" ] || [ "$_l_OP" = "--gen-ccd" ]; then
    CCD_H="$X3D_BUILD/ccd.h"
    CCD_C="$X3D_BUILD/ccd.c"
    
    {
        printf "%s" "/* Autogenerated CCD Topology Discovery Header for the X3D Toggle Project
*
* \`ccd.h\` - Header only
*
* AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
* EDIT FILE: \`ccd.sh\`
*/
                
#ifndef CCD_H
#define CCD_H
#define TOTAL_CORES $TOTAL_CORES
#define CCD1_START $CCD1_START
#define CCD0_CORE_MASK \"$CCD0_CORES\"
#define LOGICAL_TO_PHYSICAL(logical_core) ((logical_core) % (TOTAL_CORES / 2))
                
void logical_to_physical(int logical_core, int *physical_core);
void start_core_to_logical(int start_core, int *logical_core);
void total_core_to_logical(int total_core, int *logical_core);
void start_core_to_physical(int start_core, int *physical_core);
void total_core_to_physical(int total_core, int *physical_core);
void l3_cache_to_logical(int l3_cache, int *logical_core);
void l3_cache_to_physical(int l3_cache, int *physical_core);
int ccd(char *mask, int *ccd1_start, int *total_cores);
#endif
"
    } > "$CCD_H"

    {
        printf "%s" "/* Autogenerated CCD topology Mapping Suite Source for the X3D Toggle Project
*
* \`ccd.c\` - Source only
*
** AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
** EDIT FILE: \`ccd.sh\`
*/

#include \"ccd.h\"
#include \"../include/libc.h\"
#include \"../include/error.h\"
                    
static int get_physical_id(int logical_core) {
if (TOTAL_CORES < 2) return logical_core;
return logical_core % (TOTAL_CORES / 2);
}
void logical_to_physical(int l, int *p) { if(p) *p = get_physical_id(l); }
void start_core_to_logical(int s, int *l) { if(l) *l = s; }
void total_core_to_logical(int t, int *l) { if(l) *l = t; }
void start_core_to_physical(int s, int *p) { if(p) *p = get_physical_id(s); }
void total_core_to_physical(int t, int *p) { if(p) *p = get_physical_id(t); }
void l3_cache_to_logical(int i, int *l) { if(l) *l = i; }
void l3_cache_to_physical(int i, int *p) { if(p) *p = get_physical_id(i); }
int ccd(char *mask, int *ccd1_start, int *total_cores) {
if (mask) scat(mask, CCD0_CORE_MASK, 128);
if (ccd1_start) *ccd1_start = CCD1_START;
if (total_cores) *total_cores = TOTAL_CORES;
return ERR_SUCCESS;
}

// end of \`ccd.c\`
"
    } > "$CCD_C"

elif [ "$_l_OP" = "--gen-config" ]; then
    printf_step "# X3D CCD DISCOVERY NUMERICALS (AUTO-GENERATED)" \
                "CCD0_CORE_MASK=\"$CCD0_CORES\"" \
                "CCD1_START=$CCD1_START" \
                "TOTAL_CORES=$TOTAL_CORES" \
                "# END CCD DISCOVERY BLOCK"
else
    printf_string "$CCD0_CORES"
fi

## end of CCD.SH
