name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libbpf-dev libsystemd-dev libgtk-4-dev libadwaita-1-dev clang make pkg-config

    - name: Build
      run: sudo make install

    - name: Automated Setup (Full)
      run: |
        export X3D_SETUP_MODE=full
        sudo -E ./setup.sh

    - name: Run distcheck
      run: make distcheck
